#!/bin/bash
i=1
i2=0
	while [ $i -lt '10' ] 
	do
		quest=$(cat quizQ.txt | awk '{print $1}' FS="+"
	       	| head -n $i | tail -1)
		 echo $quest; 
		 if [ $a -eq "True" ]
		 	then 
			echo "Good Answer";	
		 	i=$((i+1))
		 	quest=null
		fi
       		done	

