#!/bin/bash
        echo "Please write parameter a";
        read a
	echo "Please write parameter b";
	read b

	count=0
	while [ $count -lt '3' ]
	do
	if  ! echo $a | grep [0-999] > null &&
	   !  echo $b | grep [0-999]  > null
	then 
	echo "Please write a number between 0 and 999" ;	     echo "Write a" ;read a
	echo "write b" ;read b
	count=$((count+1))
	else 
	output="$a-$b"
	echos=$(echo $output | bc)
	echo "The Difference is " $echos;
	fi
done
